# Generated by Django 3.0.2 on 2020-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_auto_20200429_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
