# Generated by Django 3.0.2 on 2020-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_bank_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
