# Generated by Django 3.0.2 on 2020-04-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0004_auto_20200429_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
